# Generated by Django 2.0.13 on 2019-06-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='capa',
            field=models.ImageField(blank=True, default=None, upload_to='images/'),
        ),
    ]
