# Generated by Django 2.0.13 on 2019-06-12 17:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_noticia_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='data',
            field=models.DateField(default=datetime.datetime(2019, 6, 12, 17, 25, 47, 522214, tzinfo=utc)),
        ),
    ]
