# Generated by Django 2.0.13 on 2019-06-12 18:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0004_auto_20190612_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='data',
            field=models.DateField(default=datetime.datetime(2019, 6, 12, 18, 18, 9, 658069, tzinfo=utc)),
        ),
    ]
