# Generated by Django 2.0.13 on 2019-07-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0008_auto_20190612_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='resumo',
            field=models.TextField(default='', max_length=500),
        ),
    ]
