# Generated by Django 2.0.13 on 2019-06-12 18:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0004_aula_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='data',
            field=models.DateField(default=datetime.datetime(2019, 6, 12, 18, 31, 49, 718673, tzinfo=utc)),
        ),
    ]
