# Generated by Django 2.0.13 on 2019-07-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0007_auto_20190612_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='descricao',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='aula',
            name='resumo',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
